name: Python Lint and Format

on: [push, pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # お使いのPythonバージョンに合わせてください

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black

    - name: Run flake8
      run: |
        # 基本的な構成でflake8を実行します。カスタム設定があればここで指定します
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --max-line-length 120

    - name: Run black
      run: |
        black . --line-length 120
